-- Dulce Crecer / Babysmart SpA
-- Asociación de Notas de Crédito con Boletas/Facturas para conciliación AR.

create table if not exists public.credit_note_document_links (
  id bigint generated by default as identity primary key,
  credit_note_id bigint not null references public.ar_documents(id) on delete cascade,
  target_document_id bigint not null references public.ar_documents(id) on delete restrict,
  allocated_amount bigint not null check (allocated_amount > 0),
  status text not null default 'activo' check (status in ('activo','anulado')),
  observation text,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (credit_note_id <> target_document_id)
);

create unique index if not exists credit_note_document_links_active_unique
on public.credit_note_document_links (credit_note_id, target_document_id)
where status = 'activo';

create index if not exists credit_note_document_links_credit_idx
on public.credit_note_document_links (credit_note_id)
where status = 'activo';

create index if not exists credit_note_document_links_target_idx
on public.credit_note_document_links (target_document_id)
where status = 'activo';

create or replace function public.validate_credit_note_document_link()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_cn public.ar_documents%rowtype;
  v_target public.ar_documents%rowtype;
  v_cn_used bigint;
  v_target_used bigint;
  v_cn_type text;
  v_target_type text;
begin
  if new.status = 'anulado' then
    new.updated_at := now();
    return new;
  end if;

  select * into v_cn from public.ar_documents where id = new.credit_note_id;
  select * into v_target from public.ar_documents where id = new.target_document_id;

  if v_cn.id is null or v_target.id is null then
    raise exception 'Documento no encontrado.';
  end if;

  v_cn_type := lower(trim(coalesce(v_cn.doc_type,'')));
  v_target_type := lower(trim(coalesce(v_target.doc_type,'')));

  if not (
    v_cn_type = '61'
    or (v_cn_type like '%nota%' and (v_cn_type like '%crédito%' or v_cn_type like '%credito%'))
  ) then
    raise exception 'El documento origen debe ser una Nota de Crédito.';
  end if;

  if not (
    v_target_type in ('41','34','boleta','boleta exenta','factura','factura exenta')
    or v_target_type like '%boleta%'
    or v_target_type like '%factura%'
  ) then
    raise exception 'La Nota de Crédito solo puede asociarse a una Boleta o Factura.';
  end if;

  select coalesce(sum(allocated_amount),0)
  into v_cn_used
  from public.credit_note_document_links
  where credit_note_id = new.credit_note_id
    and status = 'activo'
    and id is distinct from new.id;

  if v_cn_used + new.allocated_amount > abs(coalesce(v_cn.amount,0)) then
    raise exception 'El monto asociado excede el monto de la Nota de Crédito.';
  end if;

  select coalesce(sum(allocated_amount),0)
  into v_target_used
  from public.credit_note_document_links
  where target_document_id = new.target_document_id
    and status = 'activo'
    and id is distinct from new.id;

  if v_target_used + new.allocated_amount > abs(coalesce(v_target.amount,0)) then
    raise exception 'El monto asociado excede el monto del documento objetivo.';
  end if;

  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_validate_credit_note_document_link on public.credit_note_document_links;
create trigger trg_validate_credit_note_document_link
before insert or update on public.credit_note_document_links
for each row execute function public.validate_credit_note_document_link();

alter table public.credit_note_document_links enable row level security;

drop policy if exists credit_note_document_links_select_auth on public.credit_note_document_links;
create policy credit_note_document_links_select_auth
on public.credit_note_document_links for select
to authenticated
using (auth.uid() is not null);

drop policy if exists credit_note_document_links_insert_operadores on public.credit_note_document_links;
create policy credit_note_document_links_insert_operadores
on public.credit_note_document_links for insert
to authenticated
with check (public.can_write_ar());

drop policy if exists credit_note_document_links_update_operadores on public.credit_note_document_links;
create policy credit_note_document_links_update_operadores
on public.credit_note_document_links for update
to authenticated
using (public.can_write_ar())
with check (public.can_write_ar());

grant select, insert, update on public.credit_note_document_links to authenticated;
grant usage, select on sequence public.credit_note_document_links_id_seq to authenticated;
