const BASE='https://orzkndvnlrilfxdlkztf.supabase.co',KEY='sb_publishable_48G9MEMCavPDnY9-JJXSlg_jlWU5pVZ';
let session=null,profile=null,tuu=[],bank=[],docs=[],bankMatches=[],tuuMatches=[],creditNoteLinks=[],classes=[],classSessions=[],rules=[],users=[],audit=[],imports=[],currentService=null,currentRecon=null,reconList=[],importDraft=null;
const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Number(n||0)),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function msg(id,text,ok=false){const e=$(id);e.className='msg '+(ok?'ok':'err');e.textContent=text}function clearMsg(id){const e=$(id);e.className='msg';e.textContent=''}function saveSession(s){session=s;if(s)localStorage.setItem('ar_session',JSON.stringify(s));else localStorage.removeItem('ar_session')}function loadSession(){try{return JSON.parse(localStorage.getItem('ar_session')||'null')}catch{return null}}
async function auth(path,body){const r=await fetch(BASE+'/auth/v1/'+path,{method:'POST',headers:{apikey:KEY,'content-type':'application/json'},body:JSON.stringify(body)});const raw=await r.text();let j={};try{j=JSON.parse(raw)}catch{}if(!r.ok)throw new Error(j.error_description||j.msg||j.message||'Error de autenticación');return j}
async function refresh(){if(!session?.refresh_token)return false;try{const j=await auth('token?grant_type=refresh_token',{refresh_token:session.refresh_token});saveSession(j);return true}catch{saveSession(null);return false}}
async function req(url,opt={},retry=true){if(!session?.access_token)throw new Error('Sesión no iniciada');const headers={apikey:KEY,Authorization:'Bearer '+session.access_token,'content-type':'application/json',...(opt.headers||{})};let r=await fetch(url,{...opt,headers});if(r.status===401&&retry&&await refresh())return req(url,opt,false);if(!r.ok){const raw=await r.text();let j={};try{j=JSON.parse(raw)}catch{}throw new Error(j.message||j.msg||j.hint||raw||'Error de datos')}if(r.status===204)return null;const raw=await r.text();return raw?JSON.parse(raw):null}
const rest=(path,opt={})=>req(BASE+'/rest/v1/'+path,opt);async function rpc(name,body){try{return await req(BASE+'/rest/v1/rpc/'+name,{method:'POST',body:JSON.stringify(body)})}catch(e){console.warn(e)}}
async function init(){const legacy=new URLSearchParams(location.search).get('invite');if(legacy){location.replace('./activar.html?invite='+encodeURIComponent(legacy));return}session=loadSession();if(session){try{await enter()}catch(e){console.error(e);saveSession(null);msg('loginMsg','La sesión anterior venció. Ingresa nuevamente.')}}}
$('loginForm').onsubmit=async e=>{e.preventDefault();clearMsg('loginMsg');$('loginBtn').disabled=true;try{const j=await auth('token?grant_type=password',{email:$('email').value.trim(),password:$('password').value});saveSession(j);await enter()}catch(e){msg('loginMsg',e.message)}finally{$('loginBtn').disabled=false}};
$('logout').onclick=()=>{saveSession(null);location.reload()};
async function enter(){const p=await rest('profiles?id=eq.'+encodeURIComponent(session.user.id)+'&select=*');if(!p?.[0]||!p[0].active)throw new Error('Usuario no autorizado');profile=p[0];$('login').classList.add('hidden');$('app').classList.remove('hidden');$('uName').textContent=profile.full_name;$('uEmail').textContent=profile.email;$('role').textContent=profile.role;$('usersNav').style.display=profile.role==='admin'?'block':'none';await loadAll();rpc('log_ar_action',{p_action:'LOGIN',p_entity_type:'session',p_entity_id:String(profile.id),p_metadata:{}})}
async function loadAll(){const safe=async p=>{try{return await rest(p)}catch(e){console.error(p,e);return[]}};[tuu,bank,docs,bankMatches,tuuMatches,creditNoteLinks,classes,classSessions,rules,users,audit,imports]=await Promise.all([safe('tuu_transactions?select=*&order=txn_date.asc'),safe('bank_payments?select=*&order=payment_date.asc'),safe('ar_documents?select=*&order=issue_date.asc'),safe('bank_document_matches?select=*'),safe('tuu_document_matches?select=*'),safe('credit_note_document_links?select=*'),safe('classes?select=*&order=id.asc'),safe('class_sessions?select=*'),safe('service_rules?select=*&order=amount.asc'),profile.role==='admin'?safe('profiles?select=*&order=full_name.asc'):Promise.resolve([]),safe('audit_log?select=*&order=created_at.desc&limit=200'),safe('imports?select=*&order=imported_at.desc&limit=50')]);render()}
function isMp(x){return String(x.provider_id||'').startsWith('mp:')||String(x.source||'').toLowerCase().includes('mercado pago')}function tuuRows(){return tuu.filter(x=>!isMp(x))}function mpRows(){return tuu.filter(isMp)}
function activeBankMatches(){return bankMatches.filter(m=>String(m.status||'').toLowerCase()!=='anulado')}function activeTuuMatches(){return tuuMatches.filter(m=>String(m.status||'').toLowerCase()!=='anulado')}
function activeCreditNoteLinks(){return creditNoteLinks.filter(l=>String(l.status||'activo').toLowerCase()!=='anulado')}
function docCreditApplied(id){return activeCreditNoteLinks().filter(l=>l.target_document_id===id).reduce((a,l)=>a+Number(l.allocated_amount||0),0)}
function docCreditCapacity(d){return Math.max(0,Math.abs(Number(d?.amount||0))-docCreditApplied(d?.id))}
function creditNoteUsed(id){return activeCreditNoteLinks().filter(l=>l.credit_note_id===id).reduce((a,l)=>a+Number(l.allocated_amount||0),0)}
function creditNoteRemaining(d){return Math.max(0,Math.abs(Number(d?.amount||0))-creditNoteUsed(d?.id))}
function creditNoteStatusLabel(d){const used=creditNoteUsed(d.id),rem=creditNoteRemaining(d);return used<=0?'pendiente asociación':rem<=0?'asociada':'asociación parcial'}
function creditNoteTargetsLabel(d){const out=[];for(const l of activeCreditNoteLinks().filter(x=>x.credit_note_id===d.id)){const t=docs.find(x=>x.id===l.target_document_id);if(t)out.push(`${esc(t.doc_type)} ${esc(t.folio)} (${money(l.allocated_amount)})`)}return out.join('<br>')||'Sin documento asociado'}
function bankApplied(id){return activeBankMatches().filter(m=>m.bank_payment_id===id).reduce((a,m)=>a+Number(m.allocated_amount||0),0)}function bankRemaining(x){return Math.max(0,Number(x.amount||0)-bankApplied(x.id))}function bankStatus(x){const r=bankRemaining(x),a=Number(x.amount||0);return r<=0?'conciliado':r<a?'parcial':'pendiente'}
function txnRemaining(x){return String(x.ar_status).toLowerCase()==='conciliado'?0:Number(x.amount||0)}
function docApplied(id){let total=activeBankMatches().filter(m=>m.ar_document_id===id).reduce((a,m)=>a+Number(m.allocated_amount||0),0);const seen=new Set();for(const m of activeTuuMatches().filter(m=>m.ar_document_id===id)){if(seen.has(m.tuu_transaction_id))continue;const t=tuu.find(x=>x.id===m.tuu_transaction_id);if(t&&String(t.ar_status).toLowerCase()==='conciliado'){total+=Number(t.amount||0);seen.add(m.tuu_transaction_id)}}return total}
function docRemaining(d){return Math.max(0,Number(d.amount||0)-docApplied(d.id)-docCreditApplied(d.id))}
function docStatus(d){const r=docRemaining(d),a=Number(d.amount||0),ca=docCreditApplied(d.id),pa=docApplied(d.id);return r<=0?(ca>0?(pa>0?'conciliado / ajustado NC':'ajustado NC'):'conciliado'):r<a?(ca>0?'parcial / ajustado NC':'parcial'):(d.ar_status||'pendiente')}
function docLinks(d){const out=[];for(const m of activeBankMatches().filter(m=>m.ar_document_id===d.id)){const b=bank.find(x=>x.id===m.bank_payment_id);if(b)out.push(`Transferencia ${esc(b.operation)} (${money(m.allocated_amount)})`)}for(const m of activeTuuMatches().filter(m=>m.ar_document_id===d.id)){const t=tuu.find(x=>x.id===m.tuu_transaction_id);if(t)out.push(`${isMp(t)?'Mercado Pago':'Tuu'} ${esc(String(t.provider_id||''))} (${money(t.amount)})`)}for(const l of activeCreditNoteLinks().filter(l=>l.target_document_id===d.id)){const cn=docs.find(x=>x.id===l.credit_note_id);if(cn)out.push(`NC ${esc(cn.folio)} (${money(-Number(l.allocated_amount||0))})`)}return out.join('<br>')||'—'}
function txnDocs(t){const ms=activeTuuMatches().filter(m=>m.tuu_transaction_id===t.id);return ms.map(m=>{const d=docs.find(x=>x.id===m.ar_document_id);return d?`${esc(d.doc_type)} ${d.folio}`:''}).filter(Boolean).join('<br>')||'—'}
function bankDocs(b){return activeBankMatches().filter(m=>m.bank_payment_id===b.id).map(m=>{const d=docs.find(x=>x.id===m.ar_document_id);return d?`${esc(d.doc_type)} ${d.folio} (${money(m.allocated_amount)})`:''}).filter(Boolean).join('<br>')||'—'}
const SRV='ARSV1:';
function encObj(o){try{return SRV+btoa(unescape(encodeURIComponent(JSON.stringify(o))))}catch{return SRV}}
function decObj(v){v=String(v||'');const i=v.indexOf(SRV);if(i<0)return null;let x=v.slice(i+SRV.length);const cut=x.indexOf('|');if(cut>=0)x=x.slice(0,cut);try{return JSON.parse(decodeURIComponent(escape(atob(x))))}catch{return null}}
function serviceSuggestion(amount){return rules.find(r=>r.active&&Number(r.amount)===Number(amount))||null}
function normalizedService(o={}){return {service_type:o.service_type||'',periodicity:o.periodicity||'No aplica',stage:o.stage||'No aplica',frequency:Number(o.frequency||0),registration:!!o.registration,adults:Number(o.adults||0),class1:o.class1||'',day1:o.day1||'',class2:o.class2||'',day2:o.day2||'',notes:o.notes||''}}
function ruleService(amount){const r=serviceSuggestion(amount);return r?normalizedService({service_type:r.service_type,periodicity:r.periodicity,stage:r.stage,frequency:r.frequency,registration:r.registration}):normalizedService()}
function serviceFor(kind,o){if(kind==='tuu'||kind==='mp'){const has=o.final_type||o.classification_status==='confirmada';if(has)return normalizedService({service_type:o.final_type,periodicity:o.final_periodicity,stage:o.final_stage,frequency:o.final_frequency,registration:o.final_registration,adults:o.final_adults,class1:o.final_class1,day1:o.final_day1,class2:o.final_class2,day2:o.final_day2,notes:o.classification_notes});const r=ruleService(o.amount);return normalizedService({service_type:o.suggested_type||r.service_type,periodicity:o.suggested_periodicity||r.periodicity,stage:o.suggested_stage||r.stage,frequency:o.suggested_frequency??r.frequency,registration:o.suggested_registration??r.registration,class1:o.suggested_class1,day1:o.suggested_day1,class2:o.suggested_class2,day2:o.suggested_day2})}if(kind==='bank'){const d=decObj(o.service_history);if(d)return normalizedService(d);const r=ruleService(o.amount);if(o.service_history&&!String(o.service_history).startsWith(SRV))r.service_type=o.service_history;return r}if(kind==='doc'){const d=decObj(o.source_key);return d?normalizedService(d):ruleService(o.amount)}return normalizedService()}
function serviceLabel(kind,o){const x=serviceFor(kind,o);return x.service_type||'—'}
function serviceClasses(x){return [[x.class1,x.day1],[x.class2,x.day2]].filter(a=>a[0]).map(a=>a[0]+(a[1]?' · '+a[1]:'')).join(' / ')||'—'}
function entityByKind(kind,id){if(kind==='bank')return bank.find(x=>x.id===id);if(kind==='doc')return docs.find(x=>x.id===id);return tuu.find(x=>x.id===id)}
function entityAmount(kind,o){return Number(o?.amount||0)}
function serviceEntityType(kind){return kind==='bank'?'bank_payment':kind==='doc'?'ar_document':kind==='mp'?'mercadopago_transaction':'tuu_transaction'}
function docKeyWithService(d,data){const base=String(d.source_key||`doc:${d.doc_type}:${d.folio}`).replace(/\|ARSV1:[^|]+/g,'');return base+'|'+encObj(data)}


const tableSortState={};
function sortNorm(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase()}
function sortCellValue(text){const raw=String(text??'').replace(/\u00a0/g,' ').trim();if(!raw||raw==='—')return {empty:true,value:''};if(/^\d{4}-\d{2}-\d{2}/.test(raw)){const n=Date.parse(raw.slice(0,10));if(Number.isFinite(n))return {empty:false,value:n,type:'number'}}if(raw.includes('$')){const n=Number(raw.replace(/[^0-9-]/g,''));if(Number.isFinite(n))return {empty:false,value:n,type:'number'}}if(/^[-+]?\d+(?:[.,]\d+)?$/.test(raw)){const n=Number(raw.replace(',','.'));if(Number.isFinite(n))return {empty:false,value:n,type:'number'}}return {empty:false,value:sortNorm(raw),type:'text'}}
function compareSortValues(a,b,dir='asc'){if(a.empty!==b.empty)return a.empty?1:-1;if(a.empty&&b.empty)return 0;let c=0;if(a.type==='number'&&b.type==='number')c=a.value-b.value;else c=String(a.value).localeCompare(String(b.value),'es',{numeric:true,sensitivity:'base'});return dir==='desc'?-c:c}
function tableSortId(table){const body=table.querySelector('tbody[id]');return body?.id||''}
function tableHeaders(table){return [...table.querySelectorAll('thead th')]}
function setSortIndicator(table,col,dir){tableHeaders(table).forEach((th,i)=>{const base=th.dataset.sortLabel||th.textContent.replace(/[▲▼]$/,'').trim();th.dataset.sortLabel=base;if(!base)return;th.textContent=base+(i===col?(dir==='asc'?' ▲':' ▼'):'');th.classList.toggle('sort-active',i===col)})}
function sortTableManual(table,col,dir,remember=true){const body=table.querySelector('tbody[id]');if(!body)return;const rows=[...body.querySelectorAll(':scope > tr')];rows.sort((ra,rb)=>compareSortValues(sortCellValue(ra.children[col]?.textContent),sortCellValue(rb.children[col]?.textContent),dir));rows.forEach(r=>body.appendChild(r));const id=tableSortId(table);if(remember&&id)tableSortState[id]={mode:'manual',col,dir};setSortIndicator(table,col,dir)}
function sortTableDefault(table,remember=true){const body=table.querySelector('tbody[id]');if(!body)return;const headers=tableHeaders(table),labels=headers.map(h=>sortNorm(h.dataset.sortLabel||h.textContent));const pendingCol=labels.findIndex(x=>x==='pendiente'||x.includes('monto pendiente'));let amountCol=labels.findIndex(x=>x==='monto');if(amountCol<0)amountCol=labels.findIndex(x=>x==='total');const rows=[...body.querySelectorAll(':scope > tr')];rows.sort((ra,rb)=>{if(pendingCol>=0){const pa=sortCellValue(ra.children[pendingCol]?.textContent),pb=sortCellValue(rb.children[pendingCol]?.textContent),an=!pa.empty&&pa.type==='number'&&pa.value>0?1:0,bn=!pb.empty&&pb.type==='number'&&pb.value>0?1:0;if(an!==bn)return bn-an}if(amountCol>=0){const c=compareSortValues(sortCellValue(ra.children[amountCol]?.textContent),sortCellValue(rb.children[amountCol]?.textContent),'desc');if(c)return c}if(pendingCol>=0)return compareSortValues(sortCellValue(ra.children[pendingCol]?.textContent),sortCellValue(rb.children[pendingCol]?.textContent),'desc');return compareSortValues(sortCellValue(ra.children[0]?.textContent),sortCellValue(rb.children[0]?.textContent),'asc')});rows.forEach(r=>body.appendChild(r));const id=tableSortId(table);if(remember&&id)tableSortState[id]={mode:'default'};setSortIndicator(table,pendingCol>=0?pendingCol:(amountCol>=0?amountCol:0),pendingCol>=0||amountCol>=0?'desc':'asc')}
function activateTableSorting(){document.querySelectorAll('.tablewrap table').forEach(table=>{const id=tableSortId(table);if(!id)return;const headers=tableHeaders(table);headers.forEach((th,col)=>{const label=th.dataset.sortLabel||th.textContent.replace(/[▲▼]$/,'').trim();th.dataset.sortLabel=label;if(!label)return;th.classList.add('sortable-col');th.title='Ordenar por '+label;if(th.dataset.sortBound!=='1'){th.dataset.sortBound='1';th.addEventListener('click',()=>{const st=tableSortState[id],numeric=/monto|pendiente|total|cantidad|frecuencia|registros/.test(sortNorm(label));const dir=st?.mode==='manual'&&st.col===col?(st.dir==='asc'?'desc':'asc'):(numeric?'desc':'asc');sortTableManual(table,col,dir,true)})}});const st=tableSortState[id];if(st?.mode==='manual')sortTableManual(table,st.col,st.dir,false);else sortTableDefault(table,!st)})}
function scheduleTableSorting(){requestAnimationFrame(activateTableSorting)}
document.addEventListener('input',scheduleTableSorting);document.addEventListener('change',scheduleTableSorting);

function fiscalDocKind(d){const s=String(d?.doc_type||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();if(s==='61'||(s.includes('nota')&&s.includes('credito')))return 'nc';if(s==='34'||s.includes('factura'))return 'factura';if(s==='41'||s.includes('boleta'))return 'boleta';return 'otro'}
function fiscalDocAmount(d){const n=Math.abs(Number(d?.amount||0));return fiscalDocKind(d)==='nc'?-n:n}
function render(){const tr=tuuRows(),mr=mpRows(),tuuGross=tr.reduce((a,x)=>a+Number(x.amount||0),0),mpGross=mr.reduce((a,x)=>a+Number(x.amount||0),0),bankTotal=bank.reduce((a,x)=>a+Number(x.amount||0),0),paymentTotal=tuuGross+mpGross+bankTotal,fiscalDocs=docs.filter(d=>Number(d.amount||0)!==0),boletas=fiscalDocs.filter(d=>fiscalDocKind(d)==='boleta'),facturas=fiscalDocs.filter(d=>fiscalDocKind(d)==='factura'),creditos=fiscalDocs.filter(d=>fiscalDocKind(d)==='nc'),otros=fiscalDocs.filter(d=>fiscalDocKind(d)==='otro'),sumFiscal=rows=>rows.reduce((a,d)=>a+fiscalDocAmount(d),0),boletasTotal=sumFiscal(boletas),facturasTotal=sumFiscal(facturas),creditosTotal=sumFiscal(creditos),otrosTotal=sumFiscal(otros),docsNetTotal=boletasTotal+facturasTotal+creditosTotal,totalFiscalCount=boletas.length+facturas.length+creditos.length,receivableDocs=fiscalDocs.filter(d=>fiscalDocKind(d)!=='nc'&&Number(d.amount||0)>0),pendingDocs=receivableDocs.filter(d=>docRemaining(d)>0),pendingPaymentAmount=pendingDocs.reduce((a,d)=>a+docRemaining(d),0),pendingTuu=tr.filter(x=>txnRemaining(x)>0),pendingMp=mr.filter(x=>txnRemaining(x)>0),pendingBank=bank.filter(x=>bankRemaining(x)>0),pendingTuuAmount=pendingTuu.reduce((a,x)=>a+txnRemaining(x),0),pendingMpAmount=pendingMp.reduce((a,x)=>a+txnRemaining(x),0),pendingBankAmount=pendingBank.reduce((a,x)=>a+bankRemaining(x),0),pendingReconCount=pendingTuu.length+pendingMp.length+pendingBank.length,pendingReconAmount=pendingTuuAmount+pendingMpAmount+pendingBankAmount;
$('kTuu').previousElementSibling.textContent='Total pagos recibidos';$('kMp').previousElementSibling.textContent='Total documentos emitidos';$('kBank').previousElementSibling.textContent='Pendiente de pago AR';$('kDocs').previousElementSibling.textContent='Pendiente de conciliar AR';$('kPending').previousElementSibling.textContent='Operaciones pendientes';$('kTuu').textContent=money(paymentTotal);$('kMp').textContent=money(docsNetTotal);$('kBank').textContent=money(pendingPaymentAmount);$('kDocs').textContent=money(pendingReconAmount);$('kPending').textContent=pendingReconCount;
const otherRow=otros.length?`<tr><td>Otros documentos (no incluidos en total)</td><td>${otros.length}</td><td class="amount">${money(otrosTotal)}</td></tr>`:'';
$('summary').innerHTML=`<div class="summarygrid"><div class="summarybox"><span>Pagos recibidos</span><b>${money(paymentTotal)}</b><div class="subtle">Tuu ${money(tuuGross)} · Transferencias ${money(bankTotal)} · Mercado Pago ${money(mpGross)}</div></div><div class="summarybox"><span>Total documentos emitidos</span><b>${money(docsNetTotal)}</b><div class="subtle">Boletas ${money(boletasTotal)} · Facturas ${money(facturasTotal)} · Notas de crédito ${money(creditosTotal)}</div></div><div class="summarybox"><span>Saldo pendiente de pago</span><b>${money(pendingPaymentAmount)}</b><div class="subtle">${pendingDocs.length} documentos AR con saldo por cobrar</div></div><div class="summarybox"><span>Pagos pendientes de conciliar</span><b>${money(pendingReconAmount)}</b><div class="subtle">${pendingReconCount} operaciones pendientes</div></div></div><div class="grid2"><div><div class="panelhead"><h3>Validación de documentos AR</h3></div><div class="tablewrap"><table><thead><tr><th>Tipo de documento</th><th>Cantidad</th><th>Monto</th></tr></thead><tbody><tr><td>Boletas</td><td>${boletas.length}</td><td class="amount">${money(boletasTotal)}</td></tr><tr><td>Facturas</td><td>${facturas.length}</td><td class="amount">${money(facturasTotal)}</td></tr><tr><td>Notas de crédito</td><td>${creditos.length}</td><td class="amount">${money(creditosTotal)}</td></tr>${otherRow}<tr><th>Total documentos emitidos</th><th>${totalFiscalCount}</th><th class="amount">${money(docsNetTotal)}</th></tr></tbody></table></div><div class="subtle" style="margin-top:8px">Total documentos emitidos = Boletas + Facturas − Notas de crédito.</div></div><div><div class="panelhead"><h3>Pendientes de conciliación AR</h3></div><div class="tablewrap"><table><thead><tr><th>Fuente</th><th>Operaciones</th><th>Monto pendiente</th></tr></thead><tbody><tr><td>Tuu</td><td>${pendingTuu.length}</td><td class="amount">${money(pendingTuuAmount)}</td></tr><tr><td>Transferencias</td><td>${pendingBank.length}</td><td class="amount">${money(pendingBankAmount)}</td></tr><tr><td>Mercado Pago</td><td>${pendingMp.length}</td><td class="amount">${money(pendingMpAmount)}</td></tr><tr><th>Total</th><th>${pendingReconCount}</th><th class="amount">${money(pendingReconAmount)}</th></tr></tbody></table></div></div></div>`;
renderTuu();renderMp();renderBank();renderDocs();renderConsolidated();renderStatic();renderImports();scheduleTableSorting()}

function rowFilter(status,remaining){return status==='all'||(status==='pending'&&remaining>0)||(status==='reconciled'&&remaining===0)}
function renderTuu(){const q=($('qTuu').value||'').toLowerCase(),f=$('fTuu').value;$('tTuu').innerHTML=tuuRows().filter(x=>rowFilter(f,txnRemaining(x))).filter(x=>!q||[x.customer_name,x.source,x.provider_id,x.amount,x.description,serviceLabel('tuu',x)].join(' ').toLowerCase().includes(q)).map(x=>`<tr><td>${esc(x.txn_date)}</td><td>${esc(x.source||'—')}</td><td>${esc(x.customer_name||'—')}</td><td class="amount">${money(x.amount)}</td><td class="amount">${money(txnRemaining(x))}</td><td>${esc(x.description||'—')}</td><td><span class="status ${txnRemaining(x)===0?'oktxt':''}">${esc(x.ar_status)}</span></td><td>${txnDocs(x)}</td><td>${esc(serviceLabel('tuu',x))}</td><td><div class="actions">${profile.role==='lectura'?'':`${txnRemaining(x)>0?`<button class="btn primary" onclick="openRecon('tuu',${x.id})">Conciliar</button>`:''}<button class="btn light" onclick="openService('tuu',${x.id})">Servicio</button>`}</div></td></tr>`).join('')}
function renderMp(){const q=($('qMp').value||'').toLowerCase(),f=$('fMp').value;$('tMp').innerHTML=mpRows().filter(x=>rowFilter(f,txnRemaining(x))).filter(x=>!q||[x.customer_name,x.provider_id,x.amount,x.description,serviceLabel('mp',x)].join(' ').toLowerCase().includes(q)).map(x=>`<tr><td>${esc(x.txn_date)}</td><td>${esc(String(x.provider_id||'').replace(/^mp:/,''))}</td><td>${esc(x.customer_name||'—')}</td><td class="amount">${money(x.amount)}</td><td class="amount">${money(txnRemaining(x))}</td><td>${esc(x.description||'—')}</td><td><span class="status ${txnRemaining(x)===0?'oktxt':''}">${esc(x.ar_status)}</span></td><td>${txnDocs(x)}</td><td>${esc(serviceLabel('mp',x))}</td><td><div class="actions">${profile.role==='lectura'?'':`${txnRemaining(x)>0?`<button class="btn primary" onclick="openRecon('mp',${x.id})">Conciliar</button>`:''}<button class="btn light" onclick="openService('mp',${x.id})">Servicio</button>`}</div></td></tr>`).join('')}
function renderBank(){const q=($('qBank').value||'').toLowerCase(),f=$('fBank').value;$('tBank').innerHTML=bank.filter(x=>rowFilter(f,bankRemaining(x))).filter(x=>!q||[x.payer,x.operation,x.bank_origin,x.amount,serviceLabel('bank',x)].join(' ').toLowerCase().includes(q)).map(x=>`<tr><td>${esc(x.payment_date)}</td><td>${esc(x.operation)}</td><td>${esc(x.bank_origin||'—')}</td><td>${esc(x.payer||'—')}</td><td class="amount">${money(x.amount)}</td><td class="amount">${money(bankRemaining(x))}</td><td><span class="status ${bankRemaining(x)===0?'oktxt':''}">${esc(bankStatus(x))}</span></td><td>${bankDocs(x)}</td><td>${esc(serviceLabel('bank',x))}</td><td><div class="actions">${profile.role==='lectura'?'':`${bankRemaining(x)>0?`<button class="btn primary" onclick="openRecon('bank',${x.id})">Conciliar</button>`:''}<button class="btn light" onclick="openService('bank',${x.id})">Servicio</button>`}</div></td></tr>`).join('')}
function renderDocs(){const q=($('qDocs').value||'').toLowerCase(),f=$('fDocs').value;$('tDocs').innerHTML=docs.filter(d=>Number(d.amount||0)!==0).filter(d=>{const nc=fiscalDocKind(d)==='nc';return nc?f==='all':rowFilter(f,docRemaining(d))}).filter(d=>!q||[d.folio,d.origin,d.customer_name,d.doc_type,d.amount,serviceLabel('doc',d),creditNoteTargetsLabel(d)].join(' ').toLowerCase().includes(q)).map(d=>{const nc=fiscalDocKind(d)==='nc',amount=fiscalDocAmount(d),pending=nc?'—':money(docRemaining(d)),status=nc?creditNoteStatusLabel(d):docStatus(d),links=nc?creditNoteTargetsLabel(d):docLinks(d),service=nc?'—':esc(serviceLabel('doc',d));let actions='';if(profile.role!=='lectura'){if(nc){actions=`<button class="btn primary" onclick="openCreditNoteLink(${d.id})">${creditNoteRemaining(d)>0?'Asociar documento':'Ver asociación'}</button>`}else{actions=`${docRemaining(d)>0?`<button class="btn primary" onclick="openRecon('doc',${d.id})">Conciliar</button>`:''}<button class="btn light" onclick="openService('doc',${d.id})">Servicio</button>`}}return `<tr><td>${esc(d.issue_date)}</td><td>${esc(d.doc_type)}</td><td>${d.folio}</td><td class="amount ${nc?'danger':''}">${money(amount)}</td><td class="amount">${pending}</td><td>${esc(d.origin||'—')}</td><td><span class="status ${nc?(creditNoteRemaining(d)>0?'warn':'oktxt'):docRemaining(d)===0?'oktxt':''}">${esc(status)}</span></td><td>${links}</td><td>${service}</td><td><div class="actions">${actions}</div></td></tr>`}).join('')}

function renderStatic(){$('tClasses').innerHTML=classes.map(c=>`<tr><td>${esc(c.exact_label)}</td><td>${classSessions.filter(s=>s.class_id===c.id&&s.active).map(s=>esc(s.day_name)).join(', ')||'—'}</td></tr>`).join('');$('tRules').innerHTML=rules.filter(r=>r.active).map(r=>`<tr><td class="amount">${money(r.amount)}</td><td>${esc(r.service_type)}</td><td>${esc(r.periodicity)}</td><td>${r.frequency}</td><td>${r.registration?'Sí':'No'}</td><td>${esc(r.confidence)}</td></tr>`).join('');$('tUsers').innerHTML=users.map(u=>`<tr><td>${esc(u.full_name)}</td><td>${esc(u.email)}</td><td>${esc(u.role)}</td><td>${u.active?'Sí':'No'}</td></tr>`).join('');$('tAudit').innerHTML=audit.map(a=>`<tr><td>${new Date(a.created_at).toLocaleString('es-CL')}</td><td>${esc(a.user_email||'—')}</td><td>${esc(a.action)}</td><td>${esc(a.entity_type||'—')} ${esc(a.entity_id||'')}</td></tr>`).join('')}
function renderImports(){$('tImports').innerHTML=imports.map(i=>`<tr><td>${new Date(i.imported_at).toLocaleString('es-CL')}</td><td>${esc(i.source_type)}</td><td>${esc(i.file_name)}</td><td>${i.row_count??'—'}</td><td>${money(i.total_amount||0)}</td><td>${esc(users.find(u=>u.id===i.imported_by)?.email||i.metadata?.user_email||'—')}</td></tr>`).join('')||'<tr><td colspan="6">Sin importaciones registradas.</td></tr>'}
