function norm(s){return String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}function nval(o,aliases){for(const a of aliases){const k=Object.keys(o).find(k=>norm(k)===norm(a));if(k!==undefined&&o[k]!==''&&o[k]!=null)return o[k]}return null}
function num(v){if(typeof v==='number')return Math.round(v);let s=String(v??'').trim().replace(/[$\s]/g,'');if(!s)return 0;if(/^[-+]?\d{1,3}(\.\d{3})+$/.test(s))s=s.replace(/\./g,'');else if(/^[-+]?\d{1,3}(,\d{3})+$/.test(s))s=s.replace(/,/g,'');else{s=s.replace(/\.(?=\d{3}(\D|$))/g,'').replace(',','.')}const n=Number(s.replace(/[^0-9.\-]/g,''));return Number.isFinite(n)?Math.round(n):0}
function dateIso(v){if(v==null||v==='')return null;if(typeof v==='number'&&v>20000){const d=new Date(Date.UTC(1899,11,30)+v*86400000);return d.toISOString().slice(0,10)}const s=String(v).trim();let m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);if(m)return `${m[1]}-${m[2]}-${m[3]}`;m=s.match(/^(\d{1,2})[\/\-.](\d{1,2})[\/\-.](\d{4})/);if(m)return `${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;const d=new Date(s);return isNaN(d)?null:d.toISOString().slice(0,10)}
function parseCsv(text){const first=(text.split(/\r?\n/,1)[0]||''),counts={';':(first.match(/;/g)||[]).length,',':(first.match(/,/g)||[]).length,'\t':(first.match(/\t/g)||[]).length};const delim=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0][0];const rows=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++}else quoted=!quoted}else if(ch===delim&&!quoted){row.push(field);field=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(field);field='';if(row.some(x=>String(x).trim()!==''))rows.push(row);row=[]}else field+=ch}row.push(field);if(row.some(x=>String(x).trim()!==''))rows.push(row);return rows}
function colIndex(ref){const m=String(ref||'').match(/^([A-Z]+)/i);if(!m)return 0;let n=0;for(const ch of m[1].toUpperCase())n=n*26+(ch.charCodeAt(0)-64);return n-1}
async function inflateRaw(bytes){if(!('DecompressionStream'in window))throw new Error('Tu navegador no soporta lectura XLSX local. Usa CSV o un navegador actualizado.');const ds=new DecompressionStream('deflate-raw'),ab=await new Response(new Blob([bytes]).stream().pipeThrough(ds)).arrayBuffer();return new Uint8Array(ab)}
async function unzip(buffer){const v=new DataView(buffer),u=new Uint8Array(buffer),dec=new TextDecoder();let e=-1;for(let i=buffer.byteLength-22;i>=Math.max(0,buffer.byteLength-66000);i--){if(v.getUint32(i,true)===0x06054b50){e=i;break}}if(e<0)throw new Error('XLSX inválido: no se encontró el directorio ZIP.');const count=v.getUint16(e+10,true),offset=v.getUint32(e+16,true),out={};let p=offset;for(let z=0;z<count;z++){if(v.getUint32(p,true)!==0x02014b50)break;const method=v.getUint16(p+10,true),cs=v.getUint32(p+20,true),nl=v.getUint16(p+28,true),el=v.getUint16(p+30,true),cl=v.getUint16(p+32,true),lo=v.getUint32(p+42,true),name=dec.decode(u.slice(p+46,p+46+nl)),ln=v.getUint16(lo+26,true),le=v.getUint16(lo+28,true),start=lo+30+ln+le,data=u.slice(start,start+cs);out[name]=method===0?data:method===8?await inflateRaw(data):null;p+=46+nl+el+cl}return out}
function xmlText(bytes){return new TextDecoder('utf-8').decode(bytes)}function parseXml(bytes){return new DOMParser().parseFromString(xmlText(bytes),'application/xml')}
async function parseXlsx(buffer,preferred){const zip=await unzip(buffer),wb=parseXml(zip['xl/workbook.xml']),rels=parseXml(zip['xl/_rels/workbook.xml.rels']),relMap={};for(const r of rels.getElementsByTagName('Relationship'))relMap[r.getAttribute('Id')]=r.getAttribute('Target');let shared=[];if(zip['xl/sharedStrings.xml']){const sx=parseXml(zip['xl/sharedStrings.xml']);for(const si of sx.getElementsByTagName('si'))shared.push(Array.from(si.getElementsByTagName('t')).map(t=>t.textContent||'').join(''))}const sheets=Array.from(wb.getElementsByTagName('sheet')).map(s=>({name:s.getAttribute('name'),rid:s.getAttribute('r:id')||s.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id')}));let sh=sheets.find(x=>norm(x.name)===norm(preferred))||sheets[0];if(!sh)throw new Error('El XLSX no contiene hojas.');let target=relMap[sh.rid];if(!target)target='worksheets/sheet1.xml';target=target.replace(/^\//,'');if(!target.startsWith('xl/'))target='xl/'+target.replace(/^\.\//,'');const sx=parseXml(zip[target]);const rows=[];for(const r of sx.getElementsByTagName('row')){const arr=[];for(const c of r.getElementsByTagName('c')){const idx=colIndex(c.getAttribute('r')),type=c.getAttribute('t'),vn=c.getElementsByTagName('v')[0];let val='';if(type==='s'&&vn)val=shared[Number(vn.textContent)]??'';else if(type==='inlineStr')val=Array.from(c.getElementsByTagName('t')).map(t=>t.textContent||'').join('');else if(vn)val=type==='str'?vn.textContent:Number.isFinite(Number(vn.textContent))?Number(vn.textContent):vn.textContent;arr[idx]=val}rows.push(arr)}return rows}
function objectRows(rows,source){const cues={bank:['operacion','monto','banco origen'],tuu:['numero unico','fecha transaccion','monto transaccion'],mp:['monto','fecha'],docs:['tipo de documento','folio','monto total']}[source];let best=0,score=-1;for(let i=0;i<Math.min(rows.length,25);i++){const hs=rows[i].map(norm),sc=cues.reduce((a,c)=>a+(hs.some(h=>h===norm(c))?1:0),0);if(sc>score){score=sc;best=i}}const headers=rows[best].map((h,i)=>String(h??'').trim()||`col_${i+1}`);return rows.slice(best+1).filter(r=>r.some(v=>String(v??'').trim()!=='')).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])))}
function docLabel(v){const s=String(v??'').trim();return s==='41'?'Boleta Exenta':s==='34'?'Factura Exenta':s==='61'?'Nota de Crédito':s||'Documento'}
